DELETE FROM customer;
INSERT INTO customer(ID, USERNAME, PASSWORD, EMAIL, PHONE, ADDICTION) VALUES
  (1, 'Gugu', '1234', 'mail@gmail.com', '777888', 'tobacco');
INSERT INTO customer(ID, USERNAME, PASSWORD, EMAIL, PHONE, ADDICTION) VALUES
  (2, 'Jojo', '2345', 'sexy@sexyhot.com', '777888', 'tobacco');
INSERT INTO customer(ID, USERNAME, PASSWORD, EMAIL, PHONE, ADDICTION) VALUES
  (3, 'Fifi', '3456', 'mail@gmail.com', '777888', 'tobacco');

  DELETE FROM diary;
  INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (1, '2018-12-03', '10', 2);
  INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (1, '2018-12-04', '20', 4);
  INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (2, '2018-12-03', '8', 1.60);
  INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (2, '2018-12-04', '2', 0.40);
INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (2, '2018-12-05', '0', 0);
  INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (2, '2018-12-06', '4', 0.80);