DELETE FROM customer;
INSERT INTO customer(ID, USERNAME, PASSWORD, EMAIL, PHONE, ADDICTION) VALUES
  (1, 'Rui', '1234', 'mail@gmail.com', '777888', 'tobacco');
INSERT INTO customer(ID, USERNAME, PASSWORD, EMAIL, PHONE, ADDICTION) VALUES
  (2, 'Sergio', '2345', 'mail@gmail.com', '777888', 'tobacco');
INSERT INTO customer(ID, USERNAME, PASSWORD, EMAIL, PHONE, ADDICTION) VALUES
  (3, 'Bruno', '3456', 'mail@gmail.com', '777888', 'tobacco');

  DELETE FROM diary;
  INSERT INTO diary(CUSTOMER_ID,  NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (1,  '10', 2);
  INSERT INTO diary(CUSTOMER_ID, DATE, NUMBEROFSMOKEDCIGARRETTES, MONEYSPENT) VALUES
  (2, '2018-12-03', '8', 1.60);
